if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

syntax on
filetype plugin indent on
autocmd FileType json syntax match Comment +\/\/.\+$+
augroup ReactFiletypes
  autocmd!
  autocmd BufRead,BufNewFile *.jsx set filetype=javascriptreact
  autocmd BufRead,BufNewFile *.tsx set filetype=typescriptreact
augroup END

set nobackup            " Follow Coc instructions
set nowritebackup       " Follow Coc instructions
set hidden              " hide the unsaved buffer
set updatetime=400      " increase update time
set background=dark     " terminal theme is darkish hence
set expandtab           " 4 tabs per space
set shiftwidth=2        " less indenting
set tabstop=2           " wow
set scrolloff=5         " keeps cursor more centered 
set smarttab            " smart tabs and backspaces
set cindent             " wicked smart!
set cmdheight=1         " command height
set showmatch           " match brakets
set autoread            " keep on the lookout for changing files
set t_Co=256            " more colors!
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,.DS_Store
set backspace=indent,eol,start
set fillchars+=vert:\   " make the splitter prettier
set mouse=a             " allow mouse to click on nerdtree files
set number relativenumber              " add line numbers
set cursorcolumn
set cursorline
set incsearch           " match search while searching

vmap <C-c> "+y
" allow mouse to copy to clipboard
set clipboard=unnamed   " allow mouse to copy to clipboard
set hls                 " allow highlighting when using *

" Code folding
set foldmethod=indent   " fold based on indent
set foldnestmax=8       " deepest fold
set nofoldenable        " don't fold by default
set foldlevel=1         " begin fold

" Move swap file from beside the source file
set swapfile
set dir=~/.tmp

" Split
set splitbelow " better defaults
set splitright

" highlight white space at the end of line
autocmd InsertEnter * syn clear EOLWS | syn match EOLWS excludenl /\s\+\%#\@!$/
autocmd InsertLeave * syn clear EOLWS | syn match EOLWS excludenl /\s\+$/
highlight EOLWS ctermbg=red guibg=red
highlight Pmenu ctermfg=NONE ctermbg=236 cterm=NONE guifg=NONE guibg=#64666d gui=NONE

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
" Auto Complete
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}

" Navigation

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'francoiscabrol/ranger.vim'

" JavaScript/Typescript
Plug 'leafgarland/typescript-vim'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'

" Rust
Plug 'rust-lang/rust.vim'
Plug 'racer-rust/vim-racer'

" Formatters
Plug 'editorconfig/editorconfig-vim'
Plug 'sheerun/vim-polyglot'
Plug 'ruanyl/vim-sort-imports'
Plug 'prettier/vim-prettier', { 'do': 'yarn install' }

"Auto save
Plug '907th/vim-auto-save'

" Status line
Plug 'itchyny/lightline.vim'

" Git
Plug 'tpope/vim-fugitive'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" General settings
let mapleader = ","

" Prettier settings
let g:prettier#config#print_width = 80
let g:prettier#config#tab_width = 2
let g:prettier#config#use_tabs = 'false'
let g:prettier#config#semi = 'true'
let g:prettier#config#single_quote = 'true'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#jsx_bracket_same_line = 'true'
let g:prettier#config#arrow_parens = 'always'
let g:prettier#config#trailing_comma = 'none'
let g:prettier#autoformat = 0
let g:prettier#config#parser = 'flow'
let g:prettier#config#config_precedence = 'prefer-file'
let g:prettier#config#prose_wrap = 'preserve'


let g:rustfmt_autosave = 1

" Enable the auto save
let g:auto_save = 1
let g:auto_save_silent = 1
let g:auto_save_write_all_buffers = 1



" Completion settings

" Coc settings
source ~/dotfiles/config_files/vim/coc.vim

" Key Bindings
source ~/dotfiles/config_files/vim/keybindings.vim

" Lightline fixes when light line doesn't show if only one buffer
set laststatus=2
set noshowmode " gets rid of -- INSERT -- as is redundant

" Import sort
" let g:import_sort_auto = 1

" Ranger Vim
let g:ranger_map_keys = 0 " Do not use default keymapping.
let g:ranger_replace_netrw = 1
let g:ranger_command_override = 'ranger --cmd "set show_hidden=true"'


" Language specific 
source ~/dotfiles/config_files/vim/markdown.vim

" Allow local overrides
if !empty(glob('~/.local_vimrc'))
endif
if empty(glob('~/.vim/autoload/plug.vim'))
endif

